#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import { fetchSyncSchemas } from "./schema-client.js";
import type { ContentSchema, FieldDef } from "./types.js";

/** Renders an importable TypeScript schema map from moltcms schema metadata. */
export function generateSchemaTypes(schemas: readonly ContentSchema[]): string {
	const ordered = [...schemas].sort((left, right) =>
		left.content_type.localeCompare(right.content_type),
	);
	const schemaBlocks = ordered.map(renderSchema).join("\n");
	const versions = Object.fromEntries(
		ordered.map((schema) => [schema.content_type, [schema.version]]),
	);
	return `// Generated by @moltcms-sdk/client. Do not edit.\nimport type { SchemaVersionIndex } from "@moltcms-sdk/client";\n\nexport interface MoltcmsSchemas {\n${schemaBlocks}}\n\nexport const schemaVersions = ${JSON.stringify(versions, null, "\t")} as const satisfies SchemaVersionIndex<MoltcmsSchemas>;\n`;
}

function renderSchema(schema: ContentSchema): string {
	const fields = schema.fields.map(renderField).join("\n");
	return `\t${JSON.stringify(schema.content_type)}: {\n\t\t${schema.version}: {\n${fields}\n\t\t};\n\t};\n`;
}

function renderField(field: FieldDef): string {
	const property = JSON.stringify(field.name);
	const value = renderFieldValue(field);
	const definition = field.required
		? `${property}: ${value}`
		: `${property}?: ${value} | null`;
	return `\t\t\t${definition};`;
}

function renderFieldValue(field: FieldDef): string {
	switch (field.kind) {
		case "string":
		case "text":
		case "datetime":
			return "string";
		case "number":
			return "number";
		case "boolean":
			return "boolean";
		case "image":
		case "relation":
			return field.multiple ? "string[]" : "string";
		case "select": {
			const options = field.options
				.map((option) => JSON.stringify(option))
				.join(" | ");
			const value = options.length === 0 ? "never" : options;
			return field.multiple ? `(${value})[]` : value;
		}
		case "richtext":
		case "json":
			return "unknown";
	}
}

async function main(): Promise<void> {
	const args = parseArguments(process.argv.slice(2));
	const schemas = await fetchSyncSchemas(args.syncUrl, { apiKey: args.apiKey });
	await writeFile(args.output, generateSchemaTypes(schemas));
}

interface CodegenArguments {
	syncUrl: string;
	apiKey: string;
	output: string;
}

function parseArguments(args: string[]): CodegenArguments {
	const values: Record<string, string | undefined> = {};
	for (let index = 0; index < args.length; index += 2) {
		const option = args[index];
		const value = args[index + 1];
		if (
			option === undefined ||
			value === undefined ||
			!option.startsWith("--")
		) {
			throw new TypeError(
				"Usage: moltcms-sdk-codegen --sync-url <url> --api-key <key> --output <file>",
			);
		}
		values[option.slice(2)] = value;
	}
	const syncUrl = values["sync-url"];
	const apiKey = values["api-key"];
	const output = values.output;
	if (syncUrl === undefined || apiKey === undefined || output === undefined) {
		throw new TypeError(
			"Usage: moltcms-sdk-codegen --sync-url <url> --api-key <key> --output <file>",
		);
	}
	return { syncUrl, apiKey, output };
}

if (
	process.argv[1] !== undefined &&
	import.meta.url === pathToFileURL(process.argv[1]).href
) {
	main().catch((error: unknown) => {
		console.error(error);
		process.exitCode = 1;
	});
}
